### ISSUE TITLE
A question about RedBlackBST.

### ISSUE THREAD

**Issue by YRFT** [shellfly/algs4-py#2]
https://github.com/shellfly/algs4-py/blob/master/algs4/red_black_bst.py

There are two implementations of balance in RedBlackBST. One in put  method and another in balance method.  

In put method we perform "rotate left" only if the left child is black  and the right child is red. That's ok because if both children are red,  we do not need "rotate". We can just perform "color flip" to raise the  middle node up.

But in balance method, we do "rotate left" if the right child is red  and do not check the left child. I can't figure out why we don't check  the left child. In the current implementation if both children are red,  we will do some useless work, because "rotate left" then "rotate right"  will not change the tree. In my opinion, we should check the left child  as we did in put method to save some work. 

I have modified the code in balance method to include the check for the  left child and run some tests with the "check" method in booksite. All  the tests have been passed.

I have been confused for several days and appreciate any feedback.  Thank you.

**Comment by YRFT** [comment]
The `balance` method has been optimized in https://github.com/kevin-wayne/algs4/commit/5729bbb742f985ece102c2d3074421eb2d5e42c2.

I'll close this issue.

**Comment by shellfly** [comment]
@YRFT Thanks for raising this issue, the code is also updated in this repo.
