### ISSUE TITLE
Minor correction to readme

### ISSUE THREAD

**Issue by crkrenn** [shellfly/algs4-py#3]
Hello, 

Thanks for providing this library!

The code `from algs4 import Stack` in `README.md` does not work. I believe that it should read `from algs4.stack import Stack`. 

If you prefer, I can submit a pull request, but it seems like overkill for such a small change. 

Very gratefully,

-Chris

**Comment by crkrenn** [comment]
One other "bug" report: 

`bellman_ford_sp.py` requires the `EdgeWeightedDirectedCycle` class, but it is not included in your source tree. 

-Chris

**Comment by shellfly** [comment]
Thanks, I fixed the readme now, I don't have time to write the missing class these days, but I'll do once I got time, and a PR is also welcome :)

**Comment by shellfly** [comment]
This is added to master now
